name: macOS Universal Build with Precompiled Python
on:
  workflow_dispatch:
  push:
    branches: [main, master]
    paths:
      - '.github/workflows/macos_universal.yml'

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 30
    strategy:
      matrix:
        arch: [x86_64, arm64]
    env:
      PYTHON_VERSION: "3.11.13"

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python (${{ matrix.arch }})
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          architecture: ${{ matrix.arch }}

      - name: Install system dependencies
        run: |
          brew update
          brew install openssl@1.1 libffi
          echo "LDFLAGS=-L$(brew --prefix openssl@1.1)/lib -L$(brew --prefix libffi)/lib" >> $GITHUB_ENV
          echo "CPPFLAGS=-I$(brew --prefix openssl@1.1)/include -I$(brew --prefix libffi)/include" >> $GITHUB_ENV

      - name: Setup UV environment
        run: |
          python -m pip install --upgrade pip
          pip install uv
          uv venv .venv
          source .venv/bin/activate
          uv pip install -r requirements.txt pyinstaller

      - name: Build Executable (${{ matrix.arch }})
        run: |
          source .venv/bin/activate
          pyinstaller -F -n start_macos_${{ matrix.arch }} --paths=./sdk main.py
          
          # 验证二进制架构
          file dist/start_macos_${{ matrix.arch }}
          lipo -archs dist/start_macos_${{ matrix.arch }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-${{ matrix.arch }}-build
          path: |
            dist/start_macos_${{ matrix.arch }}
            sdk/.env

  create_universal:
    needs: build
    runs-on: macos-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create Universal Binary
        run: |
          # 合并两种架构的二进制
          lipo -create \
            artifacts/macos-x86_64-build/start_macos_x86_64 \
            artifacts/macos-arm64-build/start_macos_arm64 \
            -output start_macos_universal
          
          # 准备发布包
          mkdir -p dist
          mv start_macos_universal dist/
          cp artifacts/macos-x86_64-build/.env dist/
          zip -r macos_universal.zip dist/

      - name: Upload Universal Artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-universal-build
          path: macos_universal.zip

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: macos_universal.zip
          tag_name: v1.0.0
          name: Universal macOS Build
          body: |
            Supports both Intel (x86_64) and Apple Silicon (arm64)
            - Build Date: $(date)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}