name: macOS
on:
  workflow_dispatch:
  push:
    branches: [main, master]
    paths:
      - '.github/workflows/macos.yml'

jobs:
  build:
    runs-on: macos-13
    strategy:
      matrix:
        node-version: [ 12.x ]
    env:
      TZ: Asia/Shanghai
      PYTHON_VERSION: "3.9.13"
      MACOSX_DEPLOYMENT_TARGET: "10.15"

    steps:
      - uses: actions/checkout@v4
        with:
          architecture: x64

      - name: Install x86_64 Python via pyenv
        run: |
          # 安装编译依赖
          brew install openssl readline sqlite3 xz zlib tcl-tk
          
          # 安装 pyenv
          brew install pyenv
          echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.bashrc
          echo 'export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.bashrc
          echo 'eval "$(pyenv init --path)"' >> ~/.bashrc
          source ~/.bashrc
          
          # 强制安装 x86_64 版本 Python
          arch -x86_64 pyenv install $PYTHON_VERSION --verbose
          pyenv global $PYTHON_VERSION
          
          # 验证架构
          python -c "import platform; print('Python Arch:', platform.machine())"
          which python

      - name: Set up Python PATH
        run: |
          echo "$HOME/.pyenv/shims" >> $GITHUB_PATH
          echo "$HOME/.pyenv/bin" >> $GITHUB_PATH

      - name: Verify Python
        run: |
          python --version
          pip --version
          python -c "import platform; print(platform.machine())"

      - name: Install build tools
        run: |
          # 强制 x86_64 编译环境
          export ARCHFLAGS="-arch x86_64"
          export CC="clang -arch x86_64"
          export CXX="clang++ -arch x86_64"
          
          # 验证安装
          echo "当前System Python路径: $(which python)"
          echo "当前System Python版本: $(python --version)"
          echo "当前System pip版本: $(pip --version)"
          
          python -m pip install --upgrade pip
          pip install --no-cache-dir uv
          uv venv --python=3.9.9
          source .venv/bin/activate
          
          echo "当前Python路径: $(which python)"
          echo "当前Python版本: $(python --version)"
          echo "当前pip版本: $(pip --version)"
          
          uv pip install --no-cache-dir -r requirements.txt
          pyinstaller -F -n start_macos --paths=./sdk main.py
          
          # 验证架构
          file dist/start_macos
          lipo -archs dist/start_macos

      - name: Prepare artifacts
        run: |
          cp sdk/.env dist/
          # 创建 ZIP 包
          zip -r macos.zip dist/

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos-x86_64-build
          path: macos.zip

      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            macos.zip
          tag_name: v1.0.0
          name: Release v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create summary
        run: |
          echo "### 🖥️ x86_64 Build Report" >> $GITHUB_STEP_SUMMARY
          echo "- Python: $(python --version)" >> $GITHUB_STEP_SUMMARY